/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelListMode } from './modelListMode';


export interface AdminSettingsDto { 
    maxPricePerMillionTokens?: number | null;
    activeModelListMode: ModelListMode;
    startingBalance: number;
    costMultiplier: number;
    creditsPerUsd: number;
    defaultImageModel?: string | null;
}
export namespace AdminSettingsDto {
}


