/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppDto { 
    authority?: string | null;
    clientId?: string | null;
    redirectUri?: string | null;
    postLogoutRedirectUri?: string | null;
    scope?: string | null;
    version?: string | null;
}

