/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { McpTransportMode } from './mcpTransportMode';


export interface UpdateMcpServerCommand { 
    id?: string;
    name?: string;
    url?: string;
    transportMode?: McpTransportMode;
    authorizationHeader?: string | null;
    enabled?: boolean;
}
export namespace UpdateMcpServerCommand {
}


