/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface UserDto { 
    id?: string;
    email?: string | null;
    displayName?: string | null;
    avatarUrl?: string | null;
    role?: UserRole;
    creditBalance?: number;
    isLocked?: boolean;
}
export namespace UserDto {
}


