/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface UserDto { 
    id: string;
    email: string;
    displayName: string;
    avatarUrl?: string | null;
    role: UserRole;
    creditBalance: number;
    isLocked: boolean;
    preferredImageModel?: string | null;
}
export namespace UserDto {
}


