/**
 * Polyglot.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const UserRole = {
    User: 'User',
    Admin: 'Admin'
} as const;
export type UserRole = typeof UserRole[keyof typeof UserRole];

